grails-app/controllers/com/paypal/aurora/DashboardController.groovy
package com.paypal.aurora

import com.paypal.aurora.exception.RestClientRequestException
import grails.converters.JSON
import grails.converters.XML

import javax.servlet.http.HttpServletResponse

class DashboardController {
    def sessionStorageService
    
    def index = { redirect(action: 'projects', params: params) }
    def projects = {

        def tenants = sessionStorageService.tenants.sort{ it.name }
        withFormat {
            html { [tenants : tenants] }
            xml { new XML(tenants).render(response) }
            json { new JSON(tenants).render(response) }
        }
      
    }
}

grails-app/controllers/com/paypal/aurora/MeteringController.groovy
package com.paypal.aurora

import grails.converters.JSON
import grails.converters.XML

class MeteringController {

    def meteringService

    def index() {
        redirect(redirect(action: 'usages', params: params))
    }

    def usages() {
        
    }
    
    def getUsages() {
        String instanceId = params.instanceId
        int interval = Integer.valueOf(params.interval?:3600)
        int count = Integer.valueOf(params.count?:20)
        String type = params.type?:'instance:m1.tiny'
        def percents = meteringService.getUsages(type, interval, count, Boolean.valueOf(params.showCurrentTenant?:'true'))
        withFormat {
            xml { new XML(percents).render(response) }
            json { new JSON(percents).render(response) }
        }
    }

    def getMeters() {
        def meters = meteringService.meters
        withFormat {
            xml { new XML([meters:meters]).render(response) }
            json { new JSON([meters:meters]).render(response) }
        }
    }

    def getSamples() {
        def samples = meteringService.getSamples(params.type, Integer.valueOf(params.period), Boolean.valueOf(params.showCurrentTenant?:'true'))
        withFormat {
            xml { new XML(samples).render(response) }
            json { new JSON(samples).render(response) }
        }
    }

    def getProcessedSamples() {
        def samples = meteringService.getProcessedSamples(params.type, Integer.valueOf(params.period), Boolean.valueOf(params.showCurrentTenant?:'true'))
        withFormat {
            xml { new XML(samples).render(response) }
            json { new JSON(samples).render(response) }
        }
    }
}

grails-app/controllers/com/paypal/aurora/QuotaController.groovy
package com.paypal.aurora

import com.paypal.aurora.exception.RestClientRequestException
import grails.converters.JSON
import grails.converters.XML

import javax.servlet.http.HttpServletResponse

class QuotaController {

    def static allowedMethods = [list: ['GET', 'POST']]

    def quotaService

    def index = { redirect(action: 'list', params: params) }

    def list = {
        try{
            def quotas = quotaService.getAllQuotas()
            def model = [quotas : quotas]
            withFormat {
                html { [quotas : quotas] }
                xml { new XML(model).render(response) }
                json { new JSON(model).render(response) }
            }
        } catch (RestClientRequestException e){
            def error = ExceptionUtils.getExceptionMessage(e)
            response.status = ExceptionUtils.getExceptionCode(e)
            def quotas = []
            def model = [quotas : quotas, errors : error, flash: [message: error]]
            withFormat {
                html { model}
                xml { new XML(model).render(response)}
                json { new JSON(model).render(response)}
            }
        }
    }
}

grails-app/views/layouts/_auroraFooter.gsp
<div id="footer">
  <div class="container">
  <span>©2013 Aurora (Apache 2.0 Licensed).</span>
</div>
</div>

grails-app/views/layouts/_auroraHeader.gsp
<header role="banner" class="navbar navbar-inverse">
  <div class="container-full">
    <div class="navbar-header">
      <button data-target=".bs-navbar-collapse" data-toggle="collapse" type="button" class="navbar-toggle">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">
      <div id="titleLogo"><div id="aurora-text">aurora</div><div id="poweredby">powered by<span class="open">open</span><span class="stack">stack</span><span class="tm">&trade;</span></div></div>
      </a>
    </div>
    <nav role="navigation" class="">
      <shiro:isLoggedIn>
      <ul class="nav navbar-nav pull-left">
      <li <g:if test="${(pageProperty(name: 'meta.menu-level-1')) == 'myprojects'}">class="active"</g:if>>
      <g:link controller="dashboard" action="index">My Projects</g:link></li>
      </ul>
  </shiro:isLoggedIn>
      <ul class="nav navbar-nav pull-right">
        <shiro:isLoggedIn>
          <li class="dropdown"> 
            <a data-toggle="dropdown" class="dropdown-toggle" href="#"><shiro:principal/> <b class="caret"></b></a> 
            <ul class="dropdown-menu"> 
              <li><g:link elementId="signOut" controller="auth" action="signOut">Sign Out</g:link></li>
            </ul>
          </li>
        </shiro:isLoggedIn>
        <shiro:isNotLoggedIn>
          <li>
          <g:link controller="auth" action="login" class="login">Sign In</g:link>
          </li>
        </shiro:isNotLoggedIn>
      </ul>
    </nav>
  </div>
</header>

grails-app/views/layouts/_c3footer.gsp
<div id="footer">
  <div class="container">
  Your use of C3's infrastructure is subject to ebay inc.'s
  <a href="http://iweb3.corp.ebay.com/TeamSites/35188/Policy%20and%20Standards%20Wiki/Information%20Classification%20Standard.aspx">Information Classification
    Standard</a>,  and <a href="http://iweb3.corp.ebay.com/TeamSites/35188/Policy%20and%20Standards%20Wiki/Information%20Resources%20Acceptable%20Use%20Standard.aspx">Information Resources Acceptable Use Standard</a>.
</div>
</div>

grails-app/views/layouts/_occasion.gsp
<g:if test="${occasion.name() == Occasion.APRILFOOLS.name()}">
  <link rel="stylesheet" href="${resource(dir: 'js/shadowbox-3.0.3', file: 'shadowbox.css')}?v=${build}"/>
  <script defer type="text/javascript" src="${resource(dir: 'js/shadowbox-3.0.3', file: 'shadowbox.js')}?v=${build}"></script>
  <script defer type="text/javascript" src="${resource(dir: 'js', file: 'aprilfools.js')}?v=${build}"></script>
  <g:if test="${autoLaunchFullAprilFoolsJoke}">
    <script defer type="text/javascript" src="${resource(dir: 'js', file: 'aprilfoolslaunch.js')}?v=${build}"></script>
  </g:if>
</g:if>

grails-app/views/layouts/_sidebar.gsp
<%@ page import="com.paypal.aurora.OpenStackRESTService; grails.converters.JSON; com.paypal.aurora.Constant" %>
<div class="sidebar-background">
  <div class="primary-sidebar-background cos-<g:environmentCode/>"></div>
</div>
<div class="primary-sidebar">
<g:set var="menu1">${(pageProperty(name: 'meta.menu-level-1'))}</g:set>
<g:set var="menu2">${(pageProperty(name: 'meta.menu-level-2'))}</g:set>
  <!-- Main nav -->
  <ul class="nav navbar-collapse collapse navbar-collapse-primary">
        <li id="nav-compute" class="dark-nav">
          <span class="glow"></span>
          <a href="#compute-menu" data-toggle="collapse" class="accordion-toggle collapsed ">
              <i class="icon-th-list icon-2x"></i><span>Compute<i class="icon-caret-down"></i></span>
          </a>
          <ul class="collapse" id="compute-menu">
            <li id="nav-compute-instances"><g:link controller="instance" action="list"><i class="icon-th"></i> Instances</g:link></li>
            <li id="nav-compute-images"><g:link controller="image" action="list"><i class="icon-camera"></i> Images</g:link></li>
            <li id="nav-compute-flavors"><g:link controller="flavor" action="list"><i class="icon-tags"></i> Flavors</g:link></li>
          </ul>
        </li>
        <g:ifServiceEnabled name="${OpenStackRESTService.NOVA_VOLUME}">        
        <li class="dark-nav" id="nav-storage">
          <span class="glow"></span>
          <a href="#storage-menu" data-toggle="collapse" class="accordion-toggle collapsed ">
              <i class="icon-hdd icon-2x"></i><span>Storage<i class="icon-caret-down"></i></span>
          </a>
          <ul class="collapse" id="storage-menu">
              <li id="nav-storage-volumes"><g:link controller="volume" action="list"><i class="icon-hdd"></i>Volumes</g:link></li>
              <li id="nav-storage-snapshots"><g:link controller="snapshot" action="list"><i class="icon-camera-retro"></i> Snapshots</g:link></li>
          </ul>
        </li>        
        </g:ifServiceEnabled>
        <g:ifServiceEnabled name="${OpenStackRESTService.LBMS}">
        <li class="dark-nav" id="nav-lbaas">
          <span class="glow"></span>
          <a href="#lbms-menu" data-toggle="collapse" class="accordion-toggle collapsed ">
              <i class="icon-code-fork icon-2x"></i><span>Load Balancer<i class="icon-caret-down"></i></span>
          </a>
          <ul class="collapse" id="lbms-menu">
              <li id="nav-lbaas-pools"><g:link controller="lbaas" action="listPools"><i class="icon-sitemap"></i> Pools & Services</g:link></li>
              <li id="nav-lbaas-vips"><g:link controller="lbaas" action="listVips"><i class="icon-flag-alt"></i> VIPs</g:link></li>
              <li id="nav-lbaas-policies"><g:link controller="lbaas" action="listPolicies"><i class="icon-eye-open"></i> Policies</g:link></li>
              <li id="nav-lbaas-jobs"><g:link controller="lbaas" action="listJobs"><i class="icon-briefcase"></i> Jobs</g:link></li>
          </ul>
        </li>
        </g:ifServiceEnabled>
        <g:ifServiceEnabled name="${OpenStackRESTService.QUANTUM}">
        <li class="dark-nav" id="nav-networking">
          <span class="glow"></span>
          <a href="#networking-menu" data-toggle="collapse" class="accordion-toggle collapsed ">
              <i class="icon-globe icon-2x"></i><span>Networking<i class="icon-caret-down"></i></span>
          </a>
          <ul class="collapse" id="networking-menu">
              <li id="nav-networking-floatingips"><g:link controller="network" action="floatingIpList"><i class="icon-bolt"></i> Floating IPs</g:link></li>
              <li id="nav-networking-networks"><g:link controller="network" action="list"><i class="icon-sitemap"></i> Networks</g:link></li>
              <li id="nav-networking-routers"><g:link controller="router" action="list"><i class="icon-code-fork"></i> Routers</g:link></li>
          </ul>
        </li>
        </g:ifServiceEnabled>
        <g:ifServiceEnabled name="${OpenStackRESTService.HEAT}">
        <li class="dark-nav"id="nav-heat">
          <span class="glow"></span>
          <g:link controller="heat" action="list"><i class="icon-edit icon-2x"></i> <span>Cloud Formation</span></g:link>
        </li>
        </g:ifServiceEnabled>    
        <li class="dark-nav"id="nav-security">
          <span class="glow"></span>
          <a href="#security-menu" data-toggle="collapse" class="accordion-toggle collapsed ">
              <i class="icon-lock icon-2x"></i><span>Security<i class="icon-caret-down"></i></span>
          </a>
          <ul class="collapse" id="security-menu">
              <li id="nav-security-securitygroups"><g:link controller="securityGroup" action="list"><i class="icon-group"></i> Security Groups</g:link></li>
              <li id="nav-security-keypairs"><g:link controller="keypair" action="list"><i class="icon-key"></i> Keypairs</g:link></li>
          </ul>
        </li>
        <li class="dark-nav" id="nav-settings">
          <span class="glow"></span>
          <a href="#settings-menu" data-toggle="collapse" class="accordion-toggle collapsed ">
              <i class="icon-magic icon-2x"></i><span>Settings<i class="icon-caret-down"></i></span>
          </a>
          <ul class="collapse" id="settings-menu">
              <li id="nav-settings-quotausages"><g:link controller="quotaUsage" action="list"><i class="icon-tasks"></i> Quota Usages</g:link></li>
              <li id="nav-settings-quotas"><g:link controller="quota" action="list"><i class="icon-tasks"></i> Quotas</g:link></li>
              <li id="nav-settings-services"><g:link controller="openStackService" action="list"><i class="icon-cog"></i> Services</g:link></li>
              <shiro:hasRole name="${Constant.ROLE_ADMIN}">
              <li id="nav-settings-projects"><g:link controller="tenant" action="list"><i class="icon-building"></i> Projects</g:link></li>
              <li id="nav-settings-users"><g:link controller="openStackUser" action="list"><i class="icon-group"></i> Users</g:link></li>
              </shiro:hasRole>
              <li id="nav-settings-about"><g:link controller="info" action="index"><i class="icon-info-sign"></i> About</g:link></li>
          </ul>
        </li>
        <g:ifServiceEnabled name="${OpenStackRESTService.METERING}">
        <li class="dark-nav" id="nav-usages">
          <span class="glow"></span>
          <g:link controller="metering" action="usages"><i class="icon-bar-chart icon-2x"></i> <span>Usages</span></g:link>
        </li>          
        </g:ifServiceEnabled>   
  </ul>
</div>
<script>
  function showCurrentNavInSidebar() {
   var menu1 = 'nav-${menu1}'.toLowerCase();
   var level1LiItem = $('li#'+menu1);

   if(level1LiItem) {
      level1LiItem.addClass('active');
      
      if(level1LiItem.find('a.accordion-toggle').length>0 && level1LiItem.find('ul.collapse').length>0) {
        level1LiItem.find('a.accordion-toggle').removeClass('collapsed');
        level1LiItem.find('ul.collapse').addClass('in');
        var menu2 = 'nav-${menu1}-${menu2}'.toLowerCase();
        var level2LiItem = level1LiItem.find('li#'+menu2)[0];
           
        if(level2LiItem) {
          $(level2LiItem).addClass('active');
        }
      }                   
    }
  }
showCurrentNavInSidebar();
</script>

grails-app/views/layouts/main_unused.gsp
<%@ page import="com.paypal.aurora.OpenStackRESTService; grails.converters.JSON; com.paypal.aurora.Constant" %>
<!DOCTYPE html>
<html>
<head>
    <title><g:layoutTitle default="Aurora"/></title>
    <meta http-equiv="X-UA-Compatible" content="chrome=1">
    <script type="text/javascript" src="${resource(dir: 'js', file: 'jquery.js')}?v=${build}"></script>
    <script type="text/javascript" src="${resource(dir: 'js', file: 'jquery.cookie.js')}"></script>
    <script type="text/javascript">
        var cssPath = "${resource(dir: 'css')}";
        var requiredFieldsArray = {<g:each var="constraint" in="${constraints}">
            "${constraint.key}": "${constraint.value}",
            </g:each>};
        var rootContextPath = "${resource(dir: '')}";
    </script>
    <script type="text/javascript" src="${resource(dir: 'js', file: 'loader.js')}"></script>
    <!--[if IE]>
    <link rel="stylesheet" href="${resource(dir: 'css', file: 'ie.css')}?v=${build}"/>
  <![endif]-->
    <link rel="shortcut icon" href="${resource(dir: '/', file: 'favicon.ico')}" type="image/x-icon"/>
    <script type="text/javascript" src="${resource(dir: 'js', file: 'jquery-ui-1.10.3.custom.min.js')}"></script>
    <link rel="stylesheet" type="text/css" href="${resource(dir: 'css', file: 'font-awesome/css/font-awesome.css')}"/>
    <link rel="stylesheet" type="text/css" href="${resource(dir: 'css/bootstrap/css', file: 'bootstrap.min.css')}"/>
    <link rel="stylesheet" type="text/css" href="${resource(dir: 'css', file: 'ebay-navbar.css')}"/>
    <script type="text/javascript" src="${resource(dir: 'css/bootstrap/js', file: 'bootstrap.min.js')}"></script>
    <g:layoutHead/>
<style>
  .dropdown-menu a {
    color: #000000 !important;
    font-family: "HelveticaNeue-Light","Helvetica Neue Light","Helvetica Neue",Helvetica,Arial,"Lucida Grande",sans-serif !important;
    font-size: 16px !important;
    font-weight: 300 !important;
    padding: 10px 15px;
}
.dropdown-menu > li > a:hover, .dropdown-menu > li > a:focus, .dropdown-submenu:hover > a, .dropdown-submenu:focus > a {
  color: #ffffff !important;
  text-decoration: none;
  background-color: #0064D2;
  background-image: #0064D2;
  background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#0064D2), to(#0064D2));
  background-image: -webkit-linear-gradient(top, #0064D2, #0064D2);
  background-image: -o-linear-gradient(top, #0064D2, #0064D2);
  background-image: linear-gradient(to bottom, #0064D2, #0064D2);
  background-repeat: repeat-x;
  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#0064D2', endColorstr='#0064D2', GradientType=0);
}
.navbar-inverse .navbar-brand {
    color: #F0EFEC;
    padding-left: 30px;
}
  </style>
</head>
<g:render template="/layouts/c3header"/>

<body id="body">
<div id="spinner" class="spinner" style="display:none;">
    <img src="${resource(dir: 'images', file: 'spinner.gif')}" alt="Spinner"/>
</div>
<div>
<div id="browserAlert" style="display: none;">Warning! You are using an unsupported browser. Some features may not work correctly. The supported browsers are Chrome, Firefox 3.0 and higher, and Safari 3.1.2 and higher, IE8 and higher. <a href="#" id="oldBrowserAgreement">Got it! Please turn off this warning message.</a></div>
<div class="topBar">
    <div class="titlebar">
        <div class="header">
            <a href="${resource(dir: '/')}">
                <div id="titleLogo"><div id="aurora-text">aurora</div><div id="poweredby">powered by<span class="open">open</span><span class="stack">stack</span><span class="tm">&trade;</span></div></div>
            </a>
        </div>
        <g:if test="${!pageProperty(name: 'meta.hideNav')}">

        <g:set var='targetUri' value="${request.requestURL + (request.queryString ? '?' + request.queryString : '')}"/>
        <shiro:isLoggedIn>
            <div id="authentication" class="authentication">
                <span>Logged in as</span> <shiro:principal/>
                <ul>
                    <li><g:link elementId="signOut" controller="auth" action="signOut"
                                params="${[targetUri: targetUri]}">Logout</g:link></li>
                </ul>
            </div>

            <div class="tenants">
                <g:form controller="userState" action="changeDataCenter" method="POST"
                        params="${[targetUri: targetUri]}">
                    <span>Datacenter:</span> <g:chooseDatacenter title="Switch to a different datacenter" name="dataCenterName" optionKey="key" optionValue="key" />
                </g:form>
            </div>

            <div class="tenants">
                <g:form controller="userState" action="changeTenant" method="POST" params="${[targetUri: targetUri]}">
                    <span>Tenant:</span> <g:chooseTenant title="Switch to a different tenant" id="tenantId" name="tenantId" optionKey="id" optionValue="name" onchange="submit()"/>
                </g:form>
            </div>
            <div class="tenants classofservice">
                <span>Class of Service:&nbsp;</span><span><input type="text" class="text ui-corner-all env-<g:environmentCode/>" value="<g:environmentName/>" readonly="readonly" disabled="disabled"/></span>
            </div>
        </shiro:isLoggedIn>
        <shiro:isNotLoggedIn>
            <g:link controller="auth" action="login" class="login" params="${[targetUri: '/']}">Login</g:link>
        </shiro:isNotLoggedIn>
        <div class="search" title="Find entities by name">
            <form action="/search" method="GET" class="allowEnterKeySubmit">
                %{--<input type="search" results="10" autosave="aurora${env}globalsearch" name="q" placeholder="Global search by names" value="${params.q}">--}%
            </form>
        </div>
    </g:if>
    </div>
</div>
<shiro:isLoggedIn>
<div id="navigationBar">
    <g:if test="${!pageProperty(name: 'meta.hideNav')}">
        <ul id="topNav" class="appnav">
            <li class="menuButton"><g:link class="instances" elementId="nav-instance-list-root" controller="instance" action="list">Compute</g:link>
                <ul>
                    <li class="menuButton"><g:link class="instances" elementId="nav-instance-list" controller="instance"
                                                   action="list">Instances</g:link></li>
                    <li class="menuButton"><g:link class="images" elementId="nav-image-list" controller="image" action="list">Images</g:link></li>
                    <li class="menuButton"><g:link class="instanceTypes" elementId="nav-flavor-list" controller="flavor"
                                                   action="list">Flavors</g:link></li>
                </ul>
            </li>
            <g:ifServiceEnabled name="${OpenStackRESTService.NOVA_VOLUME}">
            <li class="menuButton"><g:link class="volumes" elementId="nav-volume-list-root" controller="volume" action="list">Storage</g:link>
                <ul>
                    <li class="menuButton"><g:link class="volumes" elementId="nav-volume-list" controller="volume" action="list">Volumes</g:link></li>
                    <li class="menuButton"><g:link class="volumeSnapshot" elementId="nav-snapshot-list" controller="snapshot"
                                                   action="list">Snapshots</g:link></li>
                </ul>
            </li>
            </g:ifServiceEnabled>
            <g:ifServiceEnabled name="${OpenStackRESTService.LBMS}">
                <li class="menuButton">
                    <g:link class="networks"  elementId="nav-lbaas-listPools-root" controller="lbaas" action="listPools">LBaaS</g:link>
                    <ul>
                        <li class="menuButton"><g:link class="lbaas" elementId="nav-lbaas-listPools" controller="lbaas" action="listPools">Pools & Services</g:link></li>
                        <li class="menuButton"><g:link class="vips" elementId="nav-lbaas-listVips"  controller="lbaas" action="listVips">Vips</g:link></li>
                        <li class="menuButton"><g:link class="policies" elementId="nav-lbaas-listPolicies"  controller="lbaas" action="listPolicies">Policies</g:link></li>
                        <li class="menuButton"><g:link class="jobs" elementId="nav-lbaas-listJobs" controller="lbaas" action="listJobs">Jobs</g:link></li>
                    </ul>
                </li>
            </g:ifServiceEnabled>

            <li class="menuButton"><g:link class="quantum"  elementId="nav-network-index-root" controller="network" action="index">Networking</g:link>
                <ul>
                    <li class="menuButton"><g:link class="networks"  elementId="nav-network-floatingIpList" controller="network" action="floatingIpList">Floating IPs</g:link></li>
                    <g:ifServiceEnabled name="${OpenStackRESTService.QUANTUM}">
                        <li class="menuButton"><g:link class="quantum"  elementId="nav-networks-list" controller="network" action="list">Networking</g:link></li>
                        <li class="menuButton"><g:link class="routers" elementId="nav-routers-list" controller="router" action="list">Routers</g:link></li>
                    </g:ifServiceEnabled>
                </ul>
            </li>

            <g:ifServiceEnabled name="${OpenStackRESTService.HEAT}">
                <li class="menuButton"><g:link class="heatService" elementId="nav-heat-list-root" controller="heat" action="list">Cloud Formation</g:link></li>
            </g:ifServiceEnabled>

            <li class="menuButton"><g:link class="securityGroups" elementId="nav-securityGroup-list-root" controller="securityGroup" action="list">Security</g:link>
                <ul>
                    <li class="menuButton"><g:link class="securityGroups" elementId="nav-securityGroup-list" controller="securityGroup"
                                                   action="list">Security Groups</g:link></li>
                    <li class="menuButton"><g:link class="keyPairs" elementId="nav-keypair-list" controller="keypair"
                                                   action="list">Keypairs</g:link></li>
                </ul>
            </li>
            <li class="menuButton"><g:link class="quotas" elementId="nav-quota-list-root" controller="quota" action="list">Settings</g:link>
                <ul>
                    <li class="menuButton"><g:link class="quotas" elementId="nav-quotaUsage-list" controller="quotaUsage" action="list">Quota Usage</g:link></li>
                    <li class="menuButton"><g:link class="quotas" elementId="nav-quota-list" controller="quota" action="list">Quotas</g:link></li>
                    <li class="menuButton"><g:link class="openStackService" elementId="nav-openStackService-list" controller="openStackService"
                                                   action="list">Services</g:link></li>
                    <shiro:hasRole name="${Constant.ROLE_ADMIN}">
                        <li class="menuButton"><g:link class="tenants" elementId="nav-tenant-list" controller="tenant"
                                                       action="list">Tenants</g:link></li>
                        <li class="menuButton"><g:link class="openStackUser" elementId="nav-openStackUser-list" controller="openStackUser"
                                                       action="list">Users</g:link></li>
                    </shiro:hasRole>
                    <li class="menuButton"><g:link class="about" elementId="nav-about" controller="info"
                                               action="index">About</g:link></li>
<!--                    <li class="menuButton"><g:link class="about" elementId="nav-environment" controller="info"
                                               action="environment">Environment Info</g:link></li>-->
                </ul>
            </li>
            <g:ifServiceEnabled name="${OpenStackRESTService.METERING}">
                <li class="menuButton"><g:link class="meteringService" elementId="nav-metering-root" controller="metering" action="usages">Usages</g:link></li>
            </g:ifServiceEnabled>
        </ul>
    </g:if>
    </div>
</shiro:isLoggedIn>
<div id="mainBar">
    <div id="main">
        
        <g:if test="${(pageProperty(name: 'meta.menu-level-2'))}">
          <div class="body"><h1>${pageProperty(name: 'meta.menu-level-2')}</h1></div>
        </g:if>
        <g:layoutBody/>
    </div>
</div>

<div id="footer hide">
    <div id="footer_row">
        <span>©2013 Aurora (Apache 2.0 Licensed).</span>
    </div>
</div>
<div id="confirmationDialog" title="Confirmation Dialog">  </div>
<script type="text/javascript" src="${resource(dir: 'js', file: 'jquery.browser.min.js')}"></script>
<script type="text/javascript" src="${resource(dir: 'js', file: 'ui.js')}"></script>
<script defer type="text/javascript" src="${resource(dir: 'js', file: 'custom.js')}?v=${build}"></script>
<script type="text/javascript" src="${resource(dir: 'js', file: 'combobox-widjet.js')}"></script>
<g:javascript src="back-btn.js"/>
<script type="text/javascript">
    drawBackButton("${parent}");
</script>
<!-- Script to remove the readonly attribute of the tenant drop down -->
 <script>
     jQuery(function() {
         jQuery('#select_tenantId').removeAttr('readonly');
    });
 </script>
<g:render template="/layouts/occasion"/>
</body>
</html>